
import { Doctor, Specialty } from './types';

export const MOCK_DOCTORS: Doctor[] = [
  {
    id: '1',
    name: 'Dr. Ahmad Rizal',
    specialty: Specialty.CARDIOLOGY,
    hospital: 'Gleneagles Hospital Kuala Lumpur',
    location: 'Jalan Ampang, KL',
    coords: { lat: 3.1592, lng: 101.7351 },
    rating: 4.9,
    availability: ['Monday', 'Tuesday', 'Friday'],
    experience: 15,
    image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=400&h=400',
    education: ['MBBS, UM', 'Master of Med, UM', 'Fellowship, IJN'],
    affiliations: ['National Heart Association', 'Fellow American College of Cardiology'],
    testimonials: [{ name: 'Siti Aminah', comment: 'Dr. Ahmad is professional.', rating: 5, date: 'Jan 2024' }]
  },
  {
    id: '2',
    name: 'Dr. Sarah Lim',
    specialty: Specialty.DERMATOLOGY,
    hospital: 'Sunway Medical Centre',
    location: 'Bandar Sunway, Selangor',
    coords: { lat: 3.0658, lng: 101.6074 },
    rating: 4.8,
    availability: ['Wednesday', 'Thursday', 'Saturday'],
    experience: 10,
    image: 'https://images.unsplash.com/photo-1594824476967-48c8b964273f?auto=format&fit=crop&q=80&w=400&h=400',
    education: ['MBBS, Monash', 'MRCP (UK)', 'Advanced Master, UKM'],
    affiliations: ['Malaysian Dermatological Society'],
    testimonials: [{ name: 'Wei Hong', comment: 'Cured my eczema!', rating: 5, date: 'Feb 2024' }]
  },
  {
    id: '3',
    name: 'Dr. Kavitha Raj',
    specialty: Specialty.PEDIATRICS,
    hospital: 'Pantai Hospital Bangsar',
    location: 'Bangsar, KL',
    coords: { lat: 3.1207, lng: 101.6738 },
    rating: 4.9,
    availability: ['Monday', 'Thursday'],
    experience: 12,
    image: 'https://images.unsplash.com/photo-1559839734-2b71f1536783?auto=format&fit=crop&q=80&w=400&h=400',
    education: ['MBBS, Kasturba', 'Masters, UM'],
    affiliations: ['Malaysian Paediatric Association'],
    testimonials: [{ name: 'Mei Ling', comment: 'Kids love her.', rating: 5, date: 'Mar 2024' }]
  },
  {
    id: '4',
    name: 'Dr. Mohd Faizal',
    specialty: Specialty.ORTHOPEDICS,
    hospital: 'KPJ Damansara Specialist',
    location: 'Damansara Utama, PJ',
    coords: { lat: 3.1357, lng: 101.6217 },
    rating: 4.7,
    availability: ['Tuesday', 'Saturday'],
    experience: 8,
    image: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=400&h=400',
    education: ['MD, UKM', 'MS Ortho, UM'],
    affiliations: ['MOA', 'ISAKOS'],
    testimonials: [{ name: 'Johan Ali', comment: 'Back on pitch in 6 months!', rating: 5, date: 'Feb 2024' }]
  },
  {
    id: '5',
    name: 'Dr. Jane Wong',
    specialty: Specialty.GENERAL_PRACTICE,
    hospital: 'Klinik Kesihatan Bangsar',
    location: 'Bangsar Baru, KL',
    coords: { lat: 3.1293, lng: 101.6775 },
    rating: 4.5,
    availability: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
    experience: 20,
    image: 'https://images.unsplash.com/photo-1527613426441-4da17471b66d?auto=format&fit=crop&q=80&w=400&h=400',
    education: ['MBBS, IMU'],
    affiliations: ['MMA', 'WONCA'],
    testimonials: [{ name: 'Tan Sri Lee', comment: 'Reliable family doctor.', rating: 5, date: 'Mar 2024' }]
  },
  {
    id: '6',
    name: 'Dr. Chen Wei Ming',
    specialty: Specialty.NEUROLOGY,
    hospital: 'Prince Court Medical Centre',
    location: 'Kia Peng, KL',
    coords: { lat: 3.1504, lng: 101.7196 },
    rating: 4.9,
    availability: ['Monday', 'Wednesday', 'Thursday'],
    experience: 18,
    image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=400&h=400',
    education: ['MBChB, Edinburgh', 'MRCP (UK)'],
    affiliations: ['MSN', 'World Federation of Neurology'],
    testimonials: [{ name: 'Victor Low', comment: 'Great for migraines.', rating: 5, date: 'Jan 2024' }]
  },
  {
    id: '7',
    name: 'Dr. Malini Selvaratnam',
    specialty: Specialty.GYNECOLOGY,
    hospital: 'Columbia Asia Hospital PJ',
    location: 'Petaling Jaya, Selangor',
    coords: { lat: 3.1189, lng: 101.6358 },
    rating: 4.8,
    availability: ['Tuesday', 'Thursday', 'Saturday'],
    experience: 14,
    image: 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&q=80&w=400&h=400',
    education: ['MBBS, Madras', 'Master O&G, UM'],
    affiliations: ['OGSM', 'RCOG (UK)'],
    testimonials: [{ name: 'Nabila H.', comment: 'Wonderful during pregnancy.', rating: 5, date: 'Feb 2024' }]
  },
  {
    id: '8',
    name: 'Dr. Lee Hock Seng',
    specialty: Specialty.OPHTHALMOLOGY,
    hospital: 'Tun Hussein Onn National Eye Hospital',
    location: 'Petaling Jaya, Selangor',
    coords: { lat: 3.1044, lng: 101.6445 },
    rating: 4.9,
    availability: ['Wednesday', 'Thursday', 'Friday'],
    experience: 22,
    image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=400&h=400',
    education: ['MBBS, UM', 'MS Ophthalmology, UKM'],
    affiliations: ['MSO', 'American Academy of Ophthalmology'],
    testimonials: [{ name: 'Chong K.F.', comment: 'Vision clear as day!', rating: 5, date: 'Mar 2024' }]
  },
  {
    id: '9',
    name: 'Dr. Ibrahim Yusof',
    specialty: Specialty.ORTHOPEDICS,
    hospital: 'Assunta Hospital',
    location: 'Petaling Jaya, Selangor',
    coords: { lat: 3.0954, lng: 101.6444 },
    rating: 4.6,
    availability: ['Monday', 'Tuesday', 'Thursday'],
    experience: 11,
    image: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=400&h=400',
    education: ['MD, USM', 'Master Ortho, USM'],
    affiliations: ['MOA', 'Spine Society'],
    testimonials: [{ name: 'Kamarul Ariffin', comment: 'Best spine care.', rating: 5, date: 'Feb 2024' }]
  },
  {
    id: '10',
    name: 'Dr. Stephanie Tan',
    specialty: Specialty.PEDIATRICS,
    hospital: 'Subang Jaya Medical Centre (SJMC)',
    location: 'Subang Jaya, Selangor',
    coords: { lat: 3.0768, lng: 101.5878 },
    rating: 4.9,
    availability: ['Tuesday', 'Thursday', 'Saturday'],
    experience: 16,
    image: 'https://images.unsplash.com/photo-1594824476967-48c8b964273f?auto=format&fit=crop&q=80&w=400&h=400',
    education: ['MBBS, IMU', 'MRCPCH (UK)'],
    affiliations: ['MPA', 'MMA'],
    testimonials: [{ name: 'Sarah G.', comment: 'So gentle with newborns.', rating: 5, date: 'Mar 2024' }]
  }
];

export const MALAYSIAN_STATES = [
  'Kuala Lumpur', 'Selangor', 'Penang', 'Johor', 'Perak', 'Melaka', 'Negeri Sembilan', 'Pahang', 'Terengganu', 'Kelantan', 'Kedah', 'Perlis', 'Sabah', 'Sarawak'
];
